target-version = "py313"
line-length = 120
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

[lint]
select = [
  "YTT",  # https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
  "ANN",  # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
  "ASYNC",  # https://docs.astral.sh/ruff/rules/#flake8-async-async
  "BLE",  # https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble
  "FBT",  # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt
  "B",  # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
  "A",  # https://docs.astral.sh/ruff/rules/#flake8-annotations-a
  "C4",  # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
  # "CPY", # https://docs.astral.sh/ruff/rules/#flake8-copyright-cpy
  "DTZ",  # https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
  "EM",  # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em
  "EXE",  # https://docs.astral.sh/ruff/rules/#flake8-executable-exe
  "FA",  # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
  "INT",  # https://docs.astral.sh/ruff/rules/#flake8-gettext-int
  "ISC",  # https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc
  "ICN",  # https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn
  "LOG",  # https://docs.astral.sh/ruff/rules/#flake8-logging-log
  "G",  # https://docs.astral.sh/ruff/rules/#flake8-logging-format-g
  "PIE",  # https://docs.astral.sh/ruff/rules/#flake8-pie-pie
  "PYI",  # https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi
  "PT",  # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
  "RSE",  # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
  "RET",  # https://docs.astral.sh/ruff/rules/#flake8-return-ret
  "SLF",  # https://docs.astral.sh/ruff/rules/#flake8-self-slf
  "SIM",  # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
  "SLOT",  # https://docs.astral.sh/ruff/rules/#flake8-slots-slot
  "TID",  # https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid
  "TC",  # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tc
  "ARG",  # https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
  "PTH",  # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
  "FLY",  # https://docs.astral.sh/ruff/rules/#flynt-fly
  "I",  # https://docs.astral.sh/ruff/rules/#isort-i
  "C90",  # https://docs.astral.sh/ruff/rules/#mccabe-c90
  "NPY",  # https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy
  "PD",  # https://docs.astral.sh/ruff/rules/#pandas-vet-pd
  "N",  # https://docs.astral.sh/ruff/rules/#pep8-naming-n
  "PERF",  # https://docs.astral.sh/ruff/rules/#perflint-perf
  "E",  # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
  "W",  # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
  # "DOC",  # https://docs.astral.sh/ruff/rules/#pydoclint-doc
  "F",  # https://docs.astral.sh/ruff/rules/#pyflakes-f
  "PL",  # https://docs.astral.sh/ruff/rules/#pylint-pl
  "UP",  # https://docs.astral.sh/ruff/rules/#pyupgrade-up
  "FURB",  # https://docs.astral.sh/ruff/rules/#refurb-furb
  "RUF",  # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
  "TRY",  # https://docs.astral.sh/ruff/rules/#tryceratops-try
  "D",  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
]

ignore = [
  "E501",  # https://docs.astral.sh/ruff/rules/line-too-long/
  "PLR6301",  # https://docs.astral.sh/ruff/rules/no-self-use/
  "D104",  # TODO: re-enable when all public methods have docstrings
  "D100"  # TODO: re-enable when all public modules have docstrings
]

[lint.pylint]
max-args = 8  # https://docs.astral.sh/ruff/rules/too-many-arguments/

[lint.per-file-ignores]
"tests/*" = [
  "ANN201",  # https://docs.astral.sh/ruff/rules/private-member-access/
  "SLF001",  # https://docs.astral.sh/ruff/rules/private-member-access/
  "PLR2004",  # https://docs.astral.sh/ruff/rules/magic-value-comparison/
  "PLR0913",  # https://docs.astral.sh/ruff/rules/too-many-arguments/
  "PLC2701",  # https://docs.astral.sh/ruff/rules/import-private-name/
  "PLR0914",  # https://docs.astral.sh/ruff/rules/too-many-locals
  "D",  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
]
"scripts/*" = [
  "PLC2701",  # https://docs.astral.sh/ruff/rules/import-private-name/
  "D",  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
]
"src/tenderness/__init__.py" = [
  "D",  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  "F403",  # https://docs.astral.sh/ruff/rules/undefined-local-with-import-star/
]

[lint.pydocstyle]
convention = "numpy"
