# Copyright 2026 Pavel Stepachev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import inspect
from functools import cached_property


def _defined_on(cls: type, func: object) -> bool:
    """Return True if function/property implementation is defined on cls."""
    qualname = getattr(func, "__qualname__", "")
    return qualname.startswith(f"{cls.__name__}.")


def _is_property_defined_on(cls: type, value: object) -> bool:
    if isinstance(value, cached_property):
        return _defined_on(cls, value.func)
    if not isinstance(value, property):
        return False

    fget = value.fget
    return fget is not None and _defined_on(cls, fget)


def _is_method_defined_on(cls: type, value: object) -> bool:
    return inspect.isfunction(value) and _defined_on(cls, value)


def _is_classmethod_defined_on(cls: type, value: object) -> bool:
    return isinstance(value, classmethod) and _defined_on(cls, value.__func__)


def _is_staticmethod_defined_on(cls: type, value: object) -> bool:
    return isinstance(value, staticmethod) and _defined_on(cls, value.__func__)


def _dataclass_generated_methods(cls: type) -> set[str]:
    """Returns method names auto-generated by @dataclass (not user-defined)."""
    params = cls.__dataclass_params__  # type: ignore[attr-defined]
    generated = {"__init__"}
    if params.repr:
        generated.add("__repr__")
    if params.eq:
        generated.add("__eq__")
    if params.order:
        generated.update({"__lt__", "__le__", "__gt__", "__ge__"})
    if params.frozen or params.unsafe_hash:
        generated.add("__hash__")
    if params.frozen:
        generated.update({"__setattr__", "__delattr__"})
    return generated
